primary tag: chromosome
  tag: ID
    value: chrI
  tag: Name
    value: chrI
  tag: dbxref
    value: NCBI:NC_001133
primary tag: telomere
  tag: ID
    value: TEL01L
  tag: Name
    value: TEL01L
  tag: Note
    value: Telomeric region on the left arm of Chromosome I; composed of an X element core sequence, X element combinatorial repeats, and a short terminal stretch of telomeric repeats
  tag: dbxref
    value: SGD:S000028862
  tag: display
    value: Telomeric region on the left arm of Chromosome I
primary tag: X_element
  tag: ID
    value: TEL01L_X_element
  tag: Name
    value: TEL01L_X_element
  tag: dbxref
    value: SGD:S000028862
primary tag: X_element_combinatorial_repeat
  tag: ID
    value: TEL01L_X_element_combinatorial_repeat
  tag: Name
    value: TEL01L_X_element_combinatorial_repeat
  tag: dbxref
    value: SGD:S000028862
primary tag: telomeric_repeat
  tag: ID
    value: TEL01L_telomeric_repeat
  tag: Name
    value: TEL01L_telomeric_repeat
  tag: dbxref
    value: SGD:S000028862
primary tag: gene
  tag: ID
    value: YAL069W
  tag: Name
    value: YAL069W
  tag: Note
    value: Dubious open reading frame; unlikely to encode a functional protein, based on available experimental and comparative sequence data
  tag: Ontology_term
    value: GO:0003674
    value: GO:0005575
    value: GO:0008150
  tag: dbxref
    value: SGD:S000002143
  tag: display
    value: Dubious open reading frame
  tag: orf_classification
    value: Dubious
primary tag: CDS
  tag: Name
    value: YAL069W_CDS
  tag: Parent
    value: YAL069W_mRNA
  tag: orf_classification
    value: Dubious
primary tag: mRNA
  tag: ID
    value: YAL069W_mRNA
  tag: Name
    value: YAL069W_mRNA
  tag: Parent
    value: YAL069W
primary tag: gene
  tag: ID
    value: YAL068W-A
  tag: Name
    value: YAL068W-A
  tag: Note
    value: Dubious open reading frame; unlikely to encode a functional protein, based on available experimental and comparative sequence data; identified by gene-trapping, microarray-based expression analysis, and genome-wide homology searching
  tag: Ontology_term
    value: GO:0003674
    value: GO:0005575
    value: GO:0008150
  tag: dbxref
    value: SGD:S000028594
  tag: display
    value: Dubious open reading frame
  tag: orf_classification
    value: Dubious
primary tag: CDS
  tag: Name
    value: YAL068W-A_CDS
  tag: Parent
    value: YAL068W-A_mRNA
  tag: orf_classification
    value: Dubious
primary tag: mRNA
  tag: ID
    value: YAL068W-A_mRNA
  tag: Name
    value: YAL068W-A_mRNA
  tag: Parent
